ALTER TABLE banners ADD COLUMN IF NOT EXISTS timer INTEGER DEFAULT 5000;
ALTER TABLE banners ADD COLUMN IF NOT EXISTS effect VARCHAR(50) DEFAULT 'slide';
ALTER TABLE banners ADD COLUMN IF NOT EXISTS bg_color VARCHAR(100) DEFAULT '';
